Repository inngest/inngest-js, pull requests merged in 2023-08, with the labels that each got.

#272 Assert types instead of casting in Express
  .changeset/clean-panthers-begin.md
  src/helpers/functions.ts
  src/test/helpers.ts
Labels: backport v1.x

#298 Add ability to provide Zod schemas using objects and literals
  .changeset/warm-lemons-tan.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/EventSchemas.test.ts
  packages/inngest/src/components/EventSchemas.ts
  packages/inngest/src/index.ts
Labels: feature

#202 Add Fastify serve handler
  .changeset/soft-cheetahs-lie.md
  .github/workflows/pr.yml
  examples/framework-fastify/.gitignore
  examples/framework-fastify/README.md
  examples/framework-fastify/index.ts
  examples/framework-fastify/inngest/client.ts
  examples/framework-fastify/inngest/helloWorld.ts
  examples/framework-fastify/inngest/index.ts
  examples/framework-fastify/inngest/types.ts
  examples/framework-fastify/package.json
  examples/framework-fastify/tsconfig.json
  packages/inngest/package.json
  packages/inngest/scripts/runExample.ts
  packages/inngest/src/fastify.test.ts
  packages/inngest/src/fastify.ts
  packages/inngest/src/types.ts
  pnpm-lock.yaml
Labels: prerelease/inngest
