Repository inngest/inngest-js, pull requests merged in 2023-06, with the labels that each got.

#210 Fix `NonRetriableError` not working when thrown from within a step
  .changeset/dirty-laws-enjoy.md
  src/components/InngestFunction.test.ts
  src/components/InngestFunction.ts
Labels: bug

#223 Add workflow that allows us to automatically backport merged PRs
  .github/workflows/backport.yml
Labels: backport 1.x

#224 Add automated legacy releases to `*.x` branches
  .github/workflows/release.yml
  scripts/generateReleaseConfig.js
  scripts/release.js
Labels: backport 1.x

#231 Add more info to 405s and ensure rejected GET is a 403
  .changeset/early-pots-fly.md
  src/components/InngestCommHandler.ts
  src/test/helpers.ts
Labels: backport v1.x

#253 Always add the `ts` field when sending events.
  .changeset/five-bats-begin.md
  src/components/Inngest.test.ts
  src/components/Inngest.ts
Labels: backport v1.x
