Repository inngest/inngest-js, pull requests merged in 2023-10, with the labels that each got.

#344 Remove next and beta from CI: green.
  .github/workflows/pr.yml
Labels: prerelease/inngest

#346 Hotfix: `waitForEvent` data parsing
  .changeset/many-bananas-lick.md
  packages/inngest/src/api/api.ts
  packages/inngest/src/api/schema.test.ts
  packages/inngest/src/api/schema.ts
  packages/inngest/src/components/InngestCommHandler.ts
  packages/inngest/src/helpers/functions.ts
Labels: bug

#337 Ensure `fromRecord<>()` doesn't accept clashing names
  .changeset/pretty-doors-wait.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/EventSchemas.test.ts
  packages/inngest/src/components/EventSchemas.ts
  packages/inngest/src/components/Inngest.test.ts
  packages/inngest/src/components/InngestStepTools.test.ts
  packages/inngest/src/helpers/types.ts
Labels: bug

#338 Add `debounce` config stub
  .changeset/calm-hounds-relate.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/types.ts
Labels: prerelease/inngest

#350 Separate Zod typing from library
  .changeset/wicked-ties-laugh.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/EventSchemas.ts
  packages/inngest/src/helpers/validators/zod.ts
Labels: prerelease/inngest

#354 Fix path matching types getting lost in recursive types
  .changeset/wicked-peaches-visit.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/package.json
  packages/inngest/src/components/EventSchemas.test.ts
  packages/inngest/src/helpers/types.ts
  pnpm-lock.yaml
Labels: bug, prerelease/inngest

#357 Only throw lack of event key errors when we know we're in production
  .changeset/metal-horses-invite.md
  packages/inngest/src/components/Inngest.test.ts
  packages/inngest/src/components/Inngest.ts
Labels: 🐞 bug

#359 Add displayName to response
  .changeset/seven-wasps-study.md
  packages/inngest/src/components/InngestFunction.test.ts
  packages/inngest/src/components/execution/v1.ts
  packages/inngest/src/types.ts
Labels: ⬆️ improvement

#361 Set dummy value for event key for local development
  packages/inngest/src/components/Inngest.ts
  packages/inngest/src/helpers/consts.ts
Labels: 🐞 bug

#360 INN-2152 Slim down "pretty errors" before sending to Inngest
  .changeset/cold-hairs-carry.md
  packages/inngest/package.json
  packages/inngest/src/components/execution/v1.ts
  packages/inngest/src/helpers/errors.test.ts
  packages/inngest/src/helpers/errors.ts
  pnpm-lock.yaml
Labels: ⬆️ improvement

#364 Adjust release concurrency controls
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: 💡 KTLO

#329 Add `GetStepTools<typeof inngest>` type for getting generic tooling type
  .changeset/brown-pens-drive.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/EventSchemas.test.ts
  packages/inngest/src/components/Inngest.test.ts
  packages/inngest/src/components/Inngest.ts
  packages/inngest/src/index.ts
Labels: ✨ new, prerelease/inngest

#366 Contribution
  CONTRIBUTING.md
  packages/inngest/CONTRIBUTING.md
  packages/inngest/README.md
Labels: 💡 KTLO, 🧑‍💻 dx

#370 Add multiple concurrency limits and scopes
  .changeset/itchy-geese-eat.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/types.ts
Labels: prerelease/inngest

#369 Change "No request version" log from warn to debug; previous executor v
  .changeset/tasty-hornets-matter.md
  packages/inngest/src/helpers/functions.ts
Labels: ⬆️ improvement

#371 Simplify step returns such that `JsonifyObject<>` is hidden entirely
  .changeset/brave-moose-swim.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/InngestStepTools.ts
Labels: prerelease/inngest, 🧑‍💻 dx

#374 Catch execution result handler failures, such as parsing issues
  .changeset/flat-crabs-drive.md
  packages/inngest/etc/inngest.api.md
  packages/inngest/src/components/InngestCommHandler.ts
Labels: 🐞 bug

#375 Fix `stringify()` failing to serialize `BigInt`; remove instead
  .changeset/clever-dolphins-return.md
  packages/inngest/src/components/InngestStepTools.test.ts
  packages/inngest/src/helpers/strings.test.ts
  packages/inngest/src/helpers/strings.ts
Labels: 🐞 bug
